### ISSUE TITLE
error

### ISSUE THREAD

**Issue by otniel15** [godspirit00/TextReaderUsingGcloudTTS#1]
it say " an error occured when retrieving static audio : erro : http error satus : 500

**Comment by godspirit00** [comment]
If possible, check PHP's error log. Google's PHP client library will drop error messages there.
Google's PHP client library requires a PHP component `bcmath`. Make sure that is installed.

**Comment by otniel15** [comment]
thanks, how to add another voice language?

**Comment by godspirit00** [comment]
I haven't added such feature yet, so you can do it yourself. I suppose you know some basics of coding here.
1. In `list_voices.php`:
Add the following lines before `$json=chop($json,",").']}';` 
```
$response = $client->listVoices(['languageCode'=>'zh']);
$voices = $response->getVoices();

foreach ($voices as $voice) {
    $json.='{ "name":"'.$voice->getName().'","lang":"'.$voice->getLanguageCodes()[0].'","gender":"'.$voice->getSsmlGender().'"},';
}
```
Remember to replace `zh` with your language code. 
Or if you don't need Chinese voices, simply in the existing lines for Chinese voices, replace `zh` with your language code.

2. In the HTML:
(1) Add another `else if` in the `getVoices()` function. 
Something like:
```
                    } else if (resjson.voices[key].lang.indexOf("cmn-CN") != -1) {
                        if (resjson.voices[key].name.indexOf("Wavenet") != -1) {
                            $("#zh_CN").append("<option value='" + resjson.voices[key].name + "'>(" + ssmlVoiceGender[
                                Number(resjson.voices[key].gender)] + ") " + resjson.voices[key].name.replace(
                                    "cmn-CN-Wavenet-", "") + " </option>");
                        }
                    }
```
Remember to replace `cmn-CN` with your language code. Check Google's voice list to get that.
(2) Add an option list placeholder for your language in `<select id="voice"> `
Something like:
```
        <optgroup label="Mandarin Chinese" id="zh_CN">
           
        </optgroup>
```
The value of `id` here `id="zh_CN"` needs to comply with the `$("#zh_CN")` above.
Or you can simply use the existing lines for Chinese voices and change the necessary part.

Hope the above helps.

**Comment by otniel15** [comment]
thanks for your help, it work :)
